import { Track, FolderNode, Playlist } from '@/types/music';

export const SAMPLE_TRACKS: Track[] = [
  {
    id: 'demo-track-1',
    title: 'Midnight Resonance',
    artist: 'Antigravity Soundscapes',
    album: 'Zero Gravity Vol. 1',
    year: 2026,
    genre: 'Ambient / Electronic',
    duration: 184,
    mimeType: 'audio/mp3',
    path: 'https://cdn.freesound.org/previews/682/682976_5674468-lq.mp3',
    coverArtUrl: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=300&h=300&fit=crop&q=80',
    cacheStatus: 'cloud',
    addedAt: Date.now() - 1000000,
    format: 'mp3',
  },
  {
    id: 'demo-track-2',
    title: 'Neon Horizon',
    artist: 'Cyber Pulse',
    album: 'Digital Drift',
    year: 2025,
    genre: 'Synthwave',
    duration: 215,
    mimeType: 'audio/mp3',
    path: 'https://cdn.freesound.org/previews/612/612095_5674468-lq.mp3',
    coverArtUrl: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=300&h=300&fit=crop&q=80',
    cacheStatus: 'cloud',
    addedAt: Date.now() - 800000,
    format: 'mp3',
  },
  {
    id: 'demo-track-3',
    title: 'Cloud City Echoes',
    artist: 'Aura Collective',
    album: 'Zero Gravity Vol. 1',
    year: 2026,
    genre: 'Chillstep',
    duration: 198,
    mimeType: 'audio/mp3',
    path: 'https://cdn.freesound.org/previews/682/682975_5674468-lq.mp3',
    coverArtUrl: 'https://images.unsplash.com/photo-1508700115892-45ecd05ae2ad?w=300&h=300&fit=crop&q=80',
    cacheStatus: 'cloud',
    addedAt: Date.now() - 600000,
    format: 'mp3',
  },
  {
    id: 'demo-track-4',
    title: 'Atmospheric Drift',
    artist: 'Antigravity Soundscapes',
    album: 'Deep Space Reverberations',
    year: 2026,
    genre: 'Ambient',
    duration: 160,
    mimeType: 'audio/mp3',
    path: 'https://cdn.freesound.org/previews/675/675865_5674468-lq.mp3',
    coverArtUrl: 'https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?w=300&h=300&fit=crop&q=80',
    cacheStatus: 'cached',
    cachedAt: Date.now(),
    addedAt: Date.now() - 400000,
    format: 'mp3',
  },
];

export const SAMPLE_FOLDERS: FolderNode[] = [
  {
    id: 'folder-root',
    name: 'gdrive-music-test',
    path: 'gdrive-music-test',
    children: [
      {
        id: 'folder-electronic',
        name: 'Electronic & Chill',
        path: 'gdrive-music-test/Electronic & Chill',
        parentId: 'folder-root',
        children: [],
        trackIds: ['demo-track-1', 'demo-track-2', 'demo-track-3'],
      },
      {
        id: 'folder-ambient',
        name: 'Ambient Vibes',
        path: 'gdrive-music-test/Ambient Vibes',
        parentId: 'folder-root',
        children: [],
        trackIds: ['demo-track-4'],
      },
    ],
    trackIds: ['demo-track-1', 'demo-track-2', 'demo-track-3', 'demo-track-4'],
  },
];

export const SAMPLE_PLAYLISTS: Playlist[] = [
  {
    id: 'pl-favorites',
    name: 'Featured Favorites',
    trackIds: ['demo-track-1', 'demo-track-2', 'demo-track-4'],
    createdAt: Date.now() - 500000,
    updatedAt: Date.now(),
  },
  {
    id: 'pl-ambient',
    name: 'Deep Focus Ambient',
    trackIds: ['demo-track-3', 'demo-track-4'],
    createdAt: Date.now() - 200000,
    updatedAt: Date.now(),
  },
];
